ci(tmp): test snap

diff --git a/.github/workflows/build_packages.yaml b/.github/workflows/build_packages.yaml
--- a/.github/workflows/build_packages.yaml
+++ b/.github/workflows/build_packages.yaml
@@ -69,123 +69,123 @@ permissions:
   contents: read
 
 jobs:
-  mac:
-    strategy:
-      fail-fast: false
-      matrix:
-        profile:
-          - ${{ inputs.profile }}
-        os:
-          - macos-13
-          - macos-14
-        otp:
-          - ${{ inputs.otp_vsn }}
-    runs-on: ${{ matrix.os }}
-    steps:
-    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
-      with:
-        ref: ${{ github.event.inputs.ref }}
-        fetch-depth: 0
-    - uses: ./.github/actions/package-macos
-      with:
-        profile: ${{ matrix.profile }}
-        otp: ${{ matrix.otp }}
-        os: ${{ matrix.os }}
-        apple_id_password: ${{ secrets.APPLE_ID_PASSWORD }}
-        apple_developer_identity: ${{ secrets.APPLE_DEVELOPER_IDENTITY }}
-        apple_developer_id_bundle: ${{ secrets.APPLE_DEVELOPER_ID_BUNDLE }}
-        apple_developer_id_bundle_password: ${{ secrets.APPLE_DEVELOPER_ID_BUNDLE_PASSWORD }}
-    - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
-      if: success()
-      with:
-        name: ${{ matrix.profile }}-${{ matrix.os }}-${{ matrix.otp }}
-        path: _packages/${{ matrix.profile }}/
-        retention-days: 7
+  # mac:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       profile:
+  #         - ${{ inputs.profile }}
+  #       os:
+  #         - macos-13
+  #         - macos-14
+  #       otp:
+  #         - ${{ inputs.otp_vsn }}
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #   - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
+  #     with:
+  #       ref: ${{ github.event.inputs.ref }}
+  #       fetch-depth: 0
+  #   - uses: ./.github/actions/package-macos
+  #     with:
+  #       profile: ${{ matrix.profile }}
+  #       otp: ${{ matrix.otp }}
+  #       os: ${{ matrix.os }}
+  #       apple_id_password: ${{ secrets.APPLE_ID_PASSWORD }}
+  #       apple_developer_identity: ${{ secrets.APPLE_DEVELOPER_IDENTITY }}
+  #       apple_developer_id_bundle: ${{ secrets.APPLE_DEVELOPER_ID_BUNDLE }}
+  #       apple_developer_id_bundle_password: ${{ secrets.APPLE_DEVELOPER_ID_BUNDLE_PASSWORD }}
+  #   - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
+  #     if: success()
+  #     with:
+  #       name: ${{ matrix.profile }}-${{ matrix.os }}-${{ matrix.otp }}
+  #       path: _packages/${{ matrix.profile }}/
+  #       retention-days: 7
 
-  linux:
-    runs-on: [self-hosted, ephemeral, linux, "${{ matrix.arch == 'arm64' && 'arm64' || 'x64' }}"]
-    strategy:
-      fail-fast: false
-      matrix:
-        profile:
-          - ${{ inputs.profile }}
-        os:
-          - ubuntu24.04
-          - ubuntu22.04
-          - ubuntu20.04
-          - debian12
-          - debian11
-          - debian10
-          - el9
-          - el8
-          - el7
-          - amzn2
-          - amzn2023
-        arch:
-          - amd64
-          - arm64
-        with_elixir:
-          - 'no'
-        otp:
-          - ${{ inputs.otp_vsn }}
-        builder:
-          - ${{ inputs.builder_vsn }}
-        elixir:
-          - ${{ inputs.elixir_vsn }}
-        include:
-          - profile: ${{ inputs.profile }}
-            os: ubuntu22.04
-            arch: amd64
-            with_elixir: 'yes'
-            otp: ${{ inputs.otp_vsn }}
-            builder: ${{ inputs.builder_vsn }}
-            elixir: ${{ inputs.elixir_vsn }}
+  # linux:
+  #   runs-on: [self-hosted, ephemeral, linux, "${{ matrix.arch == 'arm64' && 'arm64' || 'x64' }}"]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       profile:
+  #         - ${{ inputs.profile }}
+  #       os:
+  #         - ubuntu24.04
+  #         - ubuntu22.04
+  #         - ubuntu20.04
+  #         - debian12
+  #         - debian11
+  #         - debian10
+  #         - el9
+  #         - el8
+  #         - el7
+  #         - amzn2
+  #         - amzn2023
+  #       arch:
+  #         - amd64
+  #         - arm64
+  #       with_elixir:
+  #         - 'no'
+  #       otp:
+  #         - ${{ inputs.otp_vsn }}
+  #       builder:
+  #         - ${{ inputs.builder_vsn }}
+  #       elixir:
+  #         - ${{ inputs.elixir_vsn }}
+  #       include:
+  #         - profile: ${{ inputs.profile }}
+  #           os: ubuntu22.04
+  #           arch: amd64
+  #           with_elixir: 'yes'
+  #           otp: ${{ inputs.otp_vsn }}
+  #           builder: ${{ inputs.builder_vsn }}
+  #           elixir: ${{ inputs.elixir_vsn }}
 
-    defaults:
-      run:
-        shell: bash
+  #   defaults:
+  #     run:
+  #       shell: bash
 
-    steps:
-    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
-      with:
-        ref: ${{ github.event.inputs.ref }}
-        fetch-depth: 0
-    - name: build tgz
-      env:
-        PROFILE: ${{ matrix.profile }}
-        ARCH: ${{ matrix.arch }}
-        OS: ${{ matrix.os }}
-        IS_ELIXIR: ${{ matrix.with_elixir }}
-        BUILDER: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"
-        BUILDER_SYSTEM: force_docker
-      run: |
-        ./scripts/buildx.sh \
-          --profile $PROFILE \
-          --arch $ARCH \
-          --builder $BUILDER \
-          --elixir $IS_ELIXIR \
-          --pkgtype tgz
-    - name: build pkg
-      if: matrix.with_elixir == 'no'
-      env:
-        PROFILE: ${{ matrix.profile }}
-        ARCH: ${{ matrix.arch }}
-        OS: ${{ matrix.os }}
-        IS_ELIXIR: ${{ matrix.with_elixir }}
-        BUILDER: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"
-        BUILDER_SYSTEM: force_docker
-      run: |
-        ./scripts/buildx.sh \
-          --profile $PROFILE \
-          --arch $ARCH \
-          --builder $BUILDER \
-          --elixir $IS_ELIXIR \
-          --pkgtype pkg
-    - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
-      with:
-        name: ${{ matrix.profile }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.with_elixir == 'yes' && '-elixir' || '' }}-${{ matrix.builder }}-${{ matrix.otp }}-${{ matrix.elixir }}
-        path: _packages/${{ matrix.profile }}/
-        retention-days: 7
+  #   steps:
+  #   - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
+  #     with:
+  #       ref: ${{ github.event.inputs.ref }}
+  #       fetch-depth: 0
+  #   - name: build tgz
+  #     env:
+  #       PROFILE: ${{ matrix.profile }}
+  #       ARCH: ${{ matrix.arch }}
+  #       OS: ${{ matrix.os }}
+  #       IS_ELIXIR: ${{ matrix.with_elixir }}
+  #       BUILDER: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"
+  #       BUILDER_SYSTEM: force_docker
+  #     run: |
+  #       ./scripts/buildx.sh \
+  #         --profile $PROFILE \
+  #         --arch $ARCH \
+  #         --builder $BUILDER \
+  #         --elixir $IS_ELIXIR \
+  #         --pkgtype tgz
+  #   - name: build pkg
+  #     if: matrix.with_elixir == 'no'
+  #     env:
+  #       PROFILE: ${{ matrix.profile }}
+  #       ARCH: ${{ matrix.arch }}
+  #       OS: ${{ matrix.os }}
+  #       IS_ELIXIR: ${{ matrix.with_elixir }}
+  #       BUILDER: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"
+  #       BUILDER_SYSTEM: force_docker
+  #     run: |
+  #       ./scripts/buildx.sh \
+  #         --profile $PROFILE \
+  #         --arch $ARCH \
+  #         --builder $BUILDER \
+  #         --elixir $IS_ELIXIR \
+  #         --pkgtype pkg
+  #   - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
+  #     with:
+  #       name: ${{ matrix.profile }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.with_elixir == 'yes' && '-elixir' || '' }}-${{ matrix.builder }}-${{ matrix.otp }}-${{ matrix.elixir }}
+  #       path: _packages/${{ matrix.profile }}/
+  #       retention-days: 7
 
   snap:
     runs-on: [self-hosted, ephemeral, linux, "${{ matrix.arch == 'arm64' && 'arm64' || 'x64' }}"]
@@ -238,49 +238,49 @@ jobs:
         name: "${{ matrix.profile }}-${{ matrix.arch }}-snap"
         path: '*.snap'
 
-  publish_artifacts:
-    runs-on: ubuntu-latest
-    needs:
-      - mac
-      - linux
-    if: inputs.publish
-    strategy:
-      fail-fast: false
-      matrix:
-        profile:
-          - ${{ inputs.profile }}
-    steps:
-    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
-      with:
-        pattern: "${{ matrix.profile }}-*"
-        path: packages/${{ matrix.profile }}
-        merge-multiple: true
-    - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
-    - name: upload to aws s3
-      env:
-        PROFILE: ${{ matrix.profile }}
-        REF_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref_name }}
-        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
-        AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
-      run: |
-        set -eu
-        if [ $PROFILE = 'emqx' ]; then
-            s3dir='emqx-ce'
-        elif [ $PROFILE = 'emqx-enterprise' ]; then
-            s3dir='emqx-ee'
-        else
-            echo "unknown profile $PROFILE"
-            exit 1
-        fi
-        aws s3 cp --recursive packages/$PROFILE s3://$AWS_S3_BUCKET/$s3dir/$REF_NAME
-        aws cloudfront create-invalidation --distribution-id "$AWS_CLOUDFRONT_ID" --paths "/$s3dir/$REF_NAME/*"
+  # publish_artifacts:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - mac
+  #     - linux
+  #   if: inputs.publish
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       profile:
+  #         - ${{ inputs.profile }}
+  #   steps:
+  #   - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
+  #     with:
+  #       pattern: "${{ matrix.profile }}-*"
+  #       path: packages/${{ matrix.profile }}
+  #       merge-multiple: true
+  #   - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
+  #     with:
+  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #       aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+  #   - name: upload to aws s3
+  #     env:
+  #       PROFILE: ${{ matrix.profile }}
+  #       REF_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref_name }}
+  #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
+  #       AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
+  #     run: |
+  #       set -eu
+  #       if [ $PROFILE = 'emqx' ]; then
+  #           s3dir='emqx-ce'
+  #       elif [ $PROFILE = 'emqx-enterprise' ]; then
+  #           s3dir='emqx-ee'
+  #       else
+  #           echo "unknown profile $PROFILE"
+  #           exit 1
+  #       fi
+  #       aws s3 cp --recursive packages/$PROFILE s3://$AWS_S3_BUCKET/$s3dir/$REF_NAME
+  #       aws cloudfront create-invalidation --distribution-id "$AWS_CLOUDFRONT_ID" --paths "/$s3dir/$REF_NAME/*"
 
-    - name: Upload to snap store
-      PROFILE: ${{ matrix.profile }}
-      run: |
-        snapcraft login --with ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
-        snapcraft upload packages/$PROFILE/*.snap --release=stable
+  #   - name: Upload to snap store
+  #     PROFILE: ${{ matrix.profile }}
+  #     run: |
+  #       snapcraft login --with ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
+  #       snapcraft upload packages/$PROFILE/*.snap --release=stable
