plugins.config, ERL_LIBS

diff --git a/rel/files/emqttd b/rel/files/emqttd
--- a/rel/files/emqttd
+++ b/rel/files/emqttd
@@ -20,6 +20,8 @@ RUNNER_BASE_DIR={{runner_base_dir}}
 RUNNER_ETC_DIR={{runner_etc_dir}}
 RUNNER_LIB_DIR={{platform_lib_dir}}
 RUNNER_LOG_DIR={{runner_log_dir}}
+RUNNER_PLUGINS_DIR=$RUNNER_BASE_DIR/plugins
+
 # Note the trailing slash on $PIPE_DIR/
 PIPE_DIR={{pipe_dir}}
 RUNNER_USER={{runner_user}}
@@ -136,6 +138,13 @@ case "$1" in
         RES=`$NODETOOL_LITE chkconfig $RUNNER_ETC_DIR/app.config`
         if [ $? != 0 ]; then
             echo "Error reading $RUNNER_ETC_DIR/app.config"
+            echo $RES
+            exit 1
+        fi
+        # Sanity check the plugins.config file
+        RES=`$NODETOOL_LITE chkconfig $RUNNER_ETC_DIR/plugins.config`
+        if [ $? != 0 ]; then
+            echo "Error reading $RUNNER_ETC_DIR/plugins.config"
             echo $RES
             exit 1
         fi
@@ -256,17 +265,26 @@ case "$1" in
             echo $RES
             exit 1
         fi
+        # Sanity check the plugins.config file
+        RES=`$NODETOOL_LITE chkconfig $RUNNER_ETC_DIR/plugins.config`
+        if [ $? != 0 ]; then
+            echo "Error reading $RUNNER_ETC_DIR/plugins.config"
+            echo $RES
+            exit 1
+        fi
         # Setup beam-required vars
         ROOTDIR=$RUNNER_BASE_DIR
+        ERL_LIBS=$ROOTDIR/plugins
         BINDIR=$ROOTDIR/erts-$ERTS_VSN/bin
         EMU=beam
         PROGNAME=`echo $0 | sed 's/.*\///'`
         CMD="$BINDIR/erlexec -boot $RUNNER_BASE_DIR/releases/$APP_VSN/$SCRIPT \
-            -embedded -config $RUNNER_ETC_DIR/app.config \
+            -embedded -config $RUNNER_ETC_DIR/app.config -config $RUNNER_ETC_DIR/plugins.config \
             -pa $RUNNER_LIB_DIR/basho-patches \
             -args_file $RUNNER_ETC_DIR/vm.args -- ${1+"$@"}"
         export EMU
         export ROOTDIR
+        export ERL_LIBS
         export BINDIR
         export PROGNAME
 
@@ -284,6 +302,13 @@ case "$1" in
         RES=`$NODETOOL_LITE chkconfig $RUNNER_ETC_DIR/app.config`
         if [ $? != 0 ]; then
             echo "Error reading $RUNNER_ETC_DIR/app.config"
+            echo $RES
+            exit 1
+        fi
+        # Sanity check the plugins.config file
+        RES=`$NODETOOL_LITE chkconfig $RUNNER_ETC_DIR/plugins.config`
+        if [ $? != 0 ]; then
+            echo "Error reading $RUNNER_ETC_DIR/plugins.config"
             echo $RES
             exit 1
         fi
